In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt




movie_id = pd.read_csv("Downloads/the-movies-dataset/credits.csv")
movie_id = movie_id.drop(["cast","crew"],axis=1)
#movie_id.info()

movie_name = pd.read_csv("Downloads/the-movies-dataset/movies_metadata.csv")
#movie_name.info()

movie_name['release_date']=movie_name['release_date'].astype(str)
type(movie_name['release_date'])

C:\Users\DELL\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

pandas.core.series.Series

In [2]:
movie_name['release_date'].count()

45466

In [3]:
l=[]

In [4]:
l=movie_name['release_date'][:]

In [5]:
for i in range(45466):
    l[i]=l[i][0:4]

In [6]:
movie_name.drop('release_date',axis=1,inplace=True)

In [7]:
movie_name.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,production_countries,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,"[{'iso_3166_1': 'US', 'name': 'United States o...",373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,"[{'iso_3166_1': 'US', 'name': 'United States o...",81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [8]:
movie_name['release_year'] = l

In [9]:
movie_name.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
adult                    45466 non-null object
belongs_to_collection    4494 non-null object
budget                   45466 non-null object
genres                   45466 non-null object
homepage                 7782 non-null object
id                       45466 non-null object
imdb_id                  45449 non-null object
original_language        45455 non-null object
original_title           45466 non-null object
overview                 44512 non-null object
popularity               45461 non-null object
poster_path              45080 non-null object
production_companies     45463 non-null object
production_countries     45463 non-null object
revenue                  45460 non-null float64
runtime                  45203 non-null float64
spoken_languages         45460 non-null object
status                   45379 non-null object
tagline                  20412 non-null object
title                    45460 non-null object
video                    45460 non-null object
vote_average             45460 non-null float64
vote_count               45460 non-null float64
release_year             45466 non-null object
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [10]:
movie_name.dropna()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,release_year
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,3.521940e+08,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0,1995
68,False,"{'id': 43563, 'name': 'Friday Collection', 'po...",3500000,"[{'id': 35, 'name': 'Comedy'}]",http://www.newline.com/properties/friday.html,10634,tt0113118,en,Friday,Craig and Smokey are two guys in Los Angeles h...,...,2.821592e+07,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A lot can go down between thursday and saturda...,Friday,False,7.0,513.0,1995
69,False,"{'id': 10924, 'name': 'From Dusk Till Dawn Col...",19000000,"[{'id': 27, 'name': 'Horror'}, {'id': 28, 'nam...",http://www.miramax.com/movie/from-dusk-till-dawn/,755,tt0116367,en,From Dusk Till Dawn,Seth Gecko and his younger brother Richard are...,...,2.583662e+07,108.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,One night is all that stands between them and ...,From Dusk Till Dawn,False,6.9,1644.0,1996
153,False,"{'id': 439053, 'name': 'Brooklyn Cigar Store C...",2000000,"[{'id': 35, 'name': 'Comedy'}]",http://miramax.com/movie/blue-in-the-face/,5894,tt0112541,en,Blue in the Face,"Auggie runs a small tobacco shop in Brooklyn, ...",...,1.275000e+06,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Welcome to the planet Brooklyn.,Blue in the Face,False,6.8,28.0,1995
178,False,"{'id': 286162, 'name': 'Power Rangers Collecti...",15000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.powerrangers.com/,9070,tt0113820,en,Mighty Morphin Power Rangers: The Movie,Power up with six incredible teens who out-man...,...,6.600000e+07,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Power Is On!,Mighty Morphin Power Rangers: The Movie,False,5.2,153.0,1995
219,False,"{'id': 182813, 'name': 'Clerks Collection', 'p...",27000,"[{'id': 35, 'name': 'Comedy'}]",http://www.miramax.com/movie/clerks/,2292,tt0109445,en,Clerks,Convenience and video store clerks Dante and R...,...,3.151130e+06,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just because they serve you doesn't mean they ...,Clerks,False,7.4,769.0,1994
256,False,"{'id': 10, 'name': 'Star Wars Collection', 'po...",11000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,11,tt0076759,en,Star Wars,Princess Leia is captured and held hostage by ...,...,7.753980e+08,121.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"A long time ago in a galaxy far, far away...",Star Wars,False,8.1,6778.0,1977
309,False,"{'id': 144200, 'name': 'Swan Princess Series',...",35000000,"[{'id': 16, 'name': 'Animation'}]",http://www.sonypictures.com/movies/theswanprin...,22586,tt0111333,en,The Swan Princess,The beautiful princess Odette is transformed i...,...,9.771658e+06,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,An enchanting classic destined to capture your...,The Swan Princess,False,6.5,251.0,1994
359,False,"{'id': 94032, 'name': 'The Lion King Collectio...",45000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",http://movies.disney.com/the-lion-king,8587,tt0110357,en,The Lion King,A young lion cub named Simba can't wait to be ...,...,7.882418e+08,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Life's greatest adventure is finding your plac...,The Lion King,False,8.0,5520.0,1994
475,False,"{'id': 328, 'name': 'Jurassic Park Collection'...",63000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",http://www.jurassicpark.com/,329,tt0107290,en,Jurassic Park,A wealthy entrepreneur secretly creates a them...,...,9.201000e+08,127.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,An adventure 65 million years in the making.,Jurassic Park,False,7.6,4956.0,1993
536,False,"{'id': 422837, 'name': 'Blade Runner Collectio...",28000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://www.warnerbros.com/blade-runner,78,tt0083658,en,Blade Runner,In the smog-choked dystopian Los Angeles of 20...,...,3.313962e+07,117.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Man has made his match... now it's his problem.,Blade Runner,False,7.9,3833.0,1982
579,False,"{'id': 9888, 'name': 'Home Alone Collection', ...",18000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",https://www.foxconnect.com/home-alone-4.html,771,tt0099785,en,Home Alone,Eight-year-old Kevin McCallister makes the mos...,...,4.766847e+08,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A Family Comedy Without the Family.,Home Alone,False,7.1,2487.0,1990
581,False,"{'id': 86027, 'name': 'Aladdin Collection', 'p...",28000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://movies.disney.com/aladdin,812,tt0103639,en,Aladdin,Princess Jasmine grows tired of being forced t...,...,5.040502e+08,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Wish granted!,Aladdin,False,7.4,3495.0,1992
588,False,"{'id': 153010, 'name': 'Beauty and the Beast C...",25000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 1075...",http://disney.go.com/disneyvideos/animatedfilm...,10020,tt0101414,en,Beauty and the Beast,"Follow the adventures of Belle, a bright young...",...,3.773506e+08,84.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,The most beautiful love story ever told.,Beauty and the Beast,False,7.5,3029.0,1991
638,False,"{'id': 87359, 'name': 'Mission: Impossible Col...",80000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.missionimpossible.com/,954,tt0117060,en,Mission: Impossible,"When Ethan Hunt, the leader of a crack espiona...",...,4.576964e+08,110.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Expect the Impossible.,Mission: Impossible,False,6.7,2677.0,1996
727,False,"{'id': 529, 'name': 'Wallace & Gromit Collecti...",0,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",http://www.wallaceandgromit.com/films/a-close-...,532,tt0112691,en,A Close Shave,Wallace falls in love with wool-shop owner Wen...,...,0.000000e+00,30.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,From the Oscar-winning creator of A Grand Day ...,A Close Shave,False,7.5,223.0,1995
753,False,"{'id': 303969, 'name': 'Martin Scorsese’s Worl...",0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",http://worldcinemafoundation.org/films/touki-b...,77771,tt0070820,wo,Touki-Bouki,A cowherd with a skull-mounted motorcycle and ...,...,0.000000e+00,85.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,The Journey of the Hyena,Touki Bouki,False,7.3,10.0,1973
758,False,"{'id': 424202, 'name': 'Trainspotting Collecti...",4000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.miramax.com/movie/trainspotting/,627,tt0117951,en,Trainspotting,"Renton, deeply immersed in the Edinburgh drug ...",...,1.649108e+07,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Choose life.,Trainspotting,False,7.8,2737.0,1996
825,False,"{'id': 115838, 'name': 'Escape From ... Collec...",50000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.theofficialjohncarpenter.com/escape...,10061,tt0116225,en,Escape from L.A.,"This time, a cataclysmic temblor hits Los Ange...",...,4.227736e+07,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Snake Is Back.,Escape from L.A.,False,5.6,381.0,1996
834,False,"{'id': 230, 'name': 'The Godfather Collection'...",6000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.thegodfather.com/,238,tt0068646,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",...,2.450664e+08,175.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,An offer you can't refuse.,The Godfather,False,8.5,6024.0,1972
993,False,"{'id': 55419, 'name': 'Cinderella Collection',...",2900000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/cinderella-1950,11224,tt0042332,en,Cinderella,Cinderella has faith her dreams of a better li...,...,2.635914e+08,74.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The greatest love story ever told.,Cinderella,False,6.8,1760.0,1950
1004,False,"{'id': 100970, 'name': 'The Fox and the Hound ...",12000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",http://movies.disney.com/the-fox-and-the-hound,10948,tt0082406,en,The Fox and the Hound,When a feisty little fox named Tod is adopted ...,...,2.980000e+07,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A story of two friends who didn't know they we...,The Fox and the Hound,False,7.0,884.0,1981
1034,False,"{'id': 86027, 'name': 'Aladdin Collection', 'p...",0,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",http://movies.disney.com/aladdin-and-the-king-...,11238,tt0115491,en,Aladdin and the King of Thieves,Legendary secrets are revealed as Aladdin and ...,...,0.000000e+00,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Spectacular Adventure Continues!,Aladdin and the King of Thieves,False,6.1,494.0,1996
1056,False,"{'id': 86058, 'name': 'Dirty Dancing Collectio...",6000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",http://lionsgateathome.com/dirty-dancing,88,tt0092890,en,Dirty Dancing,Expecting the usual tedium that accompanies a ...,...,2.139543e+08,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Have the time of your life.,Dirty Dancing,False,7.1,1371.0,1987
1060,False,"{'id': 86336, 'name': 'Basic Instinct Collecti...",49000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",https://www.sonymoviechannel.com/movies/basic-...,402,tt0103772,en,Basic Instinct,A police detective is in charge of the investi...,...,3.529272e+08,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A brutal murder. A brilliant killer. A cop who...,Basic Instinct,False,6.5,869.0,1992
1094,False,"{'id': 115838, 'name': 'Escape From ... Collec...",6000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://www.theofficialjohncarpenter.com/escape...,1103,tt0082340,en,Escape from New York,"In 1997, the island of Manhattan has been wall...",...,5.024470e+07,99.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,1997. New York City is now a maximum security ...,Escape from New York,False,6.9,720.0,1981
1110,False,"{'id': 529, 'name': 'Wallace & Gromit Collecti...",0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://www.wallaceandgromit.com/films/the-wron...,531,tt0108598,en,The Wrong Trousers,Gromit finds himself being pushed out of his r...,...,0.000000e+00,30.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Winner of the 1993 Academy Award for Best Anim...,The Wrong Trousers,False,7.6,266.0,1993
1154,False,"{'id': 10, 'name': 'Star Wars Collection', 'po...",18000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,1891,tt0080684,en,The Empire Strikes Back,"The epic saga continues as Luke Skywalker, in ...",...,5.384000e+08,124.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Adventure Continues...,The Empire Strikes Back,False,8.2,5998.0,1980
1156,False,"{'id': 84, 'name': 'Indiana Jones Collection',...",18000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.indianajones.com,85,tt0082971,en,Raiders of the Lost Ark,When Dr. Indiana Jones – the tweed-suited prof...,...,3.899260e+08,115.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Indiana Jones - the new hero from the creators...,Raiders of the Lost Ark,False,7.7,3949.0,1981
1159,False,"{'id': 48317, 'name': 'The Man With No Name Co...",1200000,"[{'id': 37, 'name': 'Western'}]","http://www.mgm.com/#/our-titles/766/The-Good,-...",429,tt0060196,it,"Il buono, il brutto, il cattivo",While the Civil War rages between the Union an...,...,6.000000e+06,161.0,"[{'iso_639_1': 'it', 'name': 'Italiano'}]",Released,For three men the Civil War wasn't hell. It wa...,"The Good, the Bad and the Ugly",False,8.1,2371.0,1966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40951,False,"{'id': 115776, 'name': 'Robert Langdon Collect...",75000000,"[{'id': 53, 'name': 'Thriller'}]",http://www.infernothemovie.com/,207932,tt3062096,en,Inferno,"After waking up in a hospital with amnesia, pr...",...,2.200213e+08,121.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,His greatest challenge. Humanity's last hope.,Inferno,False,5.7,2316.0,2016
40953,False,"{'id': 426103, 'name': 'Ouija Collection', 'po...",9000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://ouijamovie.com/,335796,tt4361050,en,Ouija: Origin of Evil,"In 1965 Los Angeles, a widowed mother and her ...",...,8.170575e+07,99.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"When you talk to the other side, you never kno...",Ouija: Origin of Evil,False,5.8,735.0,2016
41053,False,"{'id': 403374, 'name': 'Jack Reacher Collectio...",60000000,"[{'id': 28, 'name': 'Action'}]",http://www.jackreachermovie.com/,343611,tt3393786,en,Jack Reacher: Never Go Back,Jack Reacher must uncover the truth behind a m...,...,1.621461e+08,118.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Justice is Coming.,Jack Reacher: Never Go Back,False,5.3,1843.0,2016
41098,False,"{'id': 47627, 'name': 'Trancers Collection', '...",0,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://www.youngwolfproductions.com/trancers6/...,50699,tt0295732,en,Trancers 6: Life After Deth,In a return to the groundbreaking original fil...,...,0.000000e+00,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Same Attitude. Different Sex.,Trancers 6: Life After Deth,False,5.4,4.0,2002
41167,False,"{'id': 423173, 'name': 'Bad Santa Collection',...",26000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",http://www.badsanta2.com/,338964,tt1798603,en,Bad Santa 2,"Fueled by cheap whiskey, greed and hatred, Wil...",...,1.778218e+07,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Giving the holidays another shot.,Bad Santa 2,False,5.0,216.0,2016
41200,False,"{'id': 425435, 'name': 'Flatland Collection', ...",0,"[{'id': 16, 'name': 'Animation'}, {'id': 878, ...",http://www.flatlandthemovie.com,337550,tt0814106,en,Flatland,Set in a world of only two dimensions inhabite...,...,0.000000e+00,36.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A Journey of Many Dimensions,Flatland,False,6.2,6.0,2007
41489,False,"{'id': 10, 'name': 'Star Wars Collection', 'po...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.starwars.com/films/rogue-one,330459,tt3748528,en,Rogue One: A Star Wars Story,A rogue band of resistance fighters unite for ...,...,1.056057e+09,133.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A Rebellion Built on Hope,Rogue One: A Star Wars Story,False,7.4,5111.0,2016
41502,False,"{'id': 2326, 'name': 'Underworld Collection', ...",35000000,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",http://www.underworldbloodwars-movie.com/,346672,tt3717252,en,Underworld: Blood Wars,Vampire death dealer Selene fends off brutal a...,...,8.109331e+07,91.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Protect the Bloodline,Underworld: Blood Wars,False,5.2,1619.0,2016
41972,False,"{'id': 52785, 'name': 'xXx Collection', 'poste...",85000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://returnofxandercage.com,47971,tt1293847,en,xXx: Return of Xander Cage,Extreme athlete turned government operative Xa...,...,3.461477e+08,107.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"There are no more patriots, just rebels and ty...",xXx: Return of Xander Cage,False,5.5,1497.0,2017
41976,False,"{'id': 325470, 'name': 'The Lego Movie Collect...",80000000,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",http://www.legobatman.com,324849,tt4116284,en,The Lego Batman Movie,In the irreverent spirit of fun that made “The...,...,3.119504e+08,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Always be yourself. Unless you can be Batman.,The Lego Batman Movie,False,7.2,1473.0,2017
42096,False,"{'id': 14563, 'name': 'The Ring Collection', '...",25000000,"[{'id': 27, 'name': 'Horror'}]",http://www.ringsmovie.com/,14564,tt0498381,en,Rings,"Julia becomes worried about her boyfriend, Hol...",...,8.308089e+07,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Evil is reborn.,Rings,False,4.8,1075.0,2017
42168,False,"{'id': 404609, 'name': 'John Wick Collection',...",40000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.johnwick.movie/,324552,tt4425200,en,John Wick: Chapter 2,John Wick is forced out of retirement by a for...,...,1.715399e+08,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Never stab the devil in the back,John Wick: Chapter 2,False,6.7,2924.0,2017
42170,False,"{'id': 453993, 'name': 'The Wolverine Collecti...",97000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",http://www.foxmovies.com/movies/logan,263115,tt3315342,en,Logan,"In the near future, a weary Logan cares for an...",...,6.168018e+08,137.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,His time has come,Logan,False,7.6,6310.0,2017
42355,False,"{'id': 344830, 'name': 'Fifty Shades Collectio...",55000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",http://www.fiftyshadesmovie.com/,341174,tt4465564,en,Fifty Shades Darker,When a wounded Christian Grey tries to entice ...,...,3.788275e+08,118.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Every fairy tale has a dark side.,Fifty Shades Darker,False,6.0,2341.0,2017
42436,False,"{'id': 436483, 'name': 'Bad Kids Collection', ...",5000000,"[{'id': 9648, 'name': 'Mystery'}, {'id': 35, '...",https://www.crestview-academy.com/,426580,tt3349578,en,Bad Kids of Crestview Academy,"It's four years later, and a new group of stud...",...,0.000000e+00,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Detention sucks but it's killer fun,Bad Kids of Crestview Academy,False,4.8,13.0,2017
42490,False,"{'id': 113589, 'name': 'The Hire', 'poster_pat...",0,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://bmwfilms.com/,417004,tt6078822,en,The Escape,After the controversial disappearance of their...,...,0.000000e+00,13.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,So that one may live,The Escape,False,7.2,6.0,2016
42902,False,"{'id': 135416, 'name': 'Prometheus Collection'...",97000000,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",https://alienuniverse.com/alien-covenant,126889,tt2316204,en,Alien: Covenant,Bound for a remote planet on the far side of t...,...,2.323802e+08,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The path to paradise begins in hell.,Alien: Covenant,False,5.7,2677.0,2017
42951,False,"{'id': 47391, 'name': 'Sleepaway Camp Collecti...",0,"[{'id': 27, 'name': 'Horror'}, {'id': 35, 'nam...",http://www.sleepawaycampmovies.com/,34311,tt0096118,en,Sleepaway Camp II: Unhappy Campers,"Angela Baker, a psychotic transsexual, escapes...",...,0.000000e+00,80.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,When you go camping just take the essentials.,Sleepaway Camp II: Unhappy Campers,False,5.8,54.0,1988
43003,False,"{'id': 237445, 'name': 'Inspector Gadget Colle...",12000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://en.wikipedia.org/wiki/Inspector_Gadget_2,19766,tt0301454,en,Inspector Gadget 2,"After capturing Claw, all the criminals have g...",...,0.000000e+00,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Inspect the unexpected.,Inspector Gadget 2,False,3.9,92.0,2003

In [11]:
movie_name.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
adult                    45466 non-null object
belongs_to_collection    4494 non-null object
budget                   45466 non-null object
genres                   45466 non-null object
homepage                 7782 non-null object
id                       45466 non-null object
imdb_id                  45449 non-null object
original_language        45455 non-null object
original_title           45466 non-null object
overview                 44512 non-null object
popularity               45461 non-null object
poster_path              45080 non-null object
production_companies     45463 non-null object
production_countries     45463 non-null object
revenue                  45460 non-null float64
runtime                  45203 non-null float64
spoken_languages         45460 non-null object
status                   45379 non-null object
tagline                  20412 non-null object
title                    45460 non-null object
video                    45460 non-null object
vote_average             45460 non-null float64
vote_count               45460 non-null float64
release_year             45466 non-null object
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [12]:
movie_name=movie_name[movie_name["release_year"]!='nan']

In [13]:
movie_name.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45379 entries, 0 to 45465
Data columns (total 24 columns):
adult                    45379 non-null object
belongs_to_collection    4491 non-null object
budget                   45379 non-null object
genres                   45379 non-null object
homepage                 7769 non-null object
id                       45379 non-null object
imdb_id                  45365 non-null object
original_language        45368 non-null object
original_title           45379 non-null object
overview                 44438 non-null object
popularity               45377 non-null object
poster_path              45040 non-null object
production_companies     45379 non-null object
production_countries     45379 non-null object
revenue                  45376 non-null float64
runtime                  45130 non-null float64
spoken_languages         45376 non-null object
status                   45296 non-null object
tagline                  20398 non-null object
title                    45376 non-null object
video                    45376 non-null object
vote_average             45376 non-null float64
vote_count               45376 non-null float64
release_year             45379 non-null object
dtypes: float64(4), object(20)
memory usage: 8.7+ MB

In [14]:
movie_name = movie_name[['id','original_title','release_year']]

In [15]:
movie_name.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45379 entries, 0 to 45465
Data columns (total 3 columns):
id                45379 non-null object
original_title    45379 non-null object
release_year      45379 non-null object
dtypes: object(3)
memory usage: 1.4+ MB

In [16]:
movie_name['release_year'] = movie_name['release_year'].astype(str).astype(int)

In [17]:
movie_name = movie_name[movie_name['release_year']>2005]

In [18]:
movie_name.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18449 entries, 868 to 45465
Data columns (total 3 columns):
id                18449 non-null object
original_title    18449 non-null object
release_year      18449 non-null int32
dtypes: int32(1), object(2)
memory usage: 504.5+ KB

In [19]:
movie_name = movie_name[movie_name['id']!='1997-08-20']
movie_name = movie_name[movie_name['id']!='2012-09-29']
movie_name = movie_name[movie_name['id']!='2014-01-01']

In [20]:
movie_name.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18449 entries, 868 to 45465
Data columns (total 3 columns):
id                18449 non-null object
original_title    18449 non-null object
release_year      18449 non-null int32
dtypes: int32(1), object(2)
memory usage: 504.5+ KB

In [21]:
movie_name['id'] = movie_name['id'].astype(str).astype(int)

In [22]:
movie_id_name = pd.merge(movie_id,movie_name,on='id')

In [23]:
movie_id_name.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18483 entries, 0 to 18482
Data columns (total 3 columns):
id                18483 non-null int64
original_title    18483 non-null object
release_year      18483 non-null int32
dtypes: int32(1), int64(1), object(1)
memory usage: 505.4+ KB

In [24]:
movie_rating = pd.read_csv("Downloads/the-movies-dataset/ratings.csv")
movie_rating.drop("timestamp",axis=1,inplace=True)
movie_rating.columns = ["UserId",'id','rating']
df = pd.merge(movie_id_name,movie_rating,on='id')
df.head()

       id original_title  release_year  UserId  rating
0  136558   Kingdom Come          2011   45811     1.0
1  136558   Kingdom Come          2011   98787     1.5
2  136558   Kingdom Come          2011  228943     2.0
3  136558   Kingdom Come          2011  258253     3.0
4   78022    Da wu sheng          2011   13772     2.5

In [25]:
df.groupby("original_title")['rating'].mean().sort_values(ascending=False)
df.groupby("original_title")['rating'].count().sort_values(ascending=False)

original_title
License to Wed                                60024
Silent Hill                                   50375
Confession of a Child of the Century          39600
Bridge to Terabithia                          38672
My Name Is Bruce                              31260
Knallhart                                     27417
Rocky Balboa                                  25752
Local Color                                   25245
Reign Over Me                                 24467
The Dark                                      24292
Notes on a Scandal                            24137
Persepolis                                    24040
Stellet Licht                                 24011
La science des rêves                          21672
The Garden of Eden                            20924
Ober                                          20746
Der rote Elvis                                20409
Boat                                          20276
The Good Shepherd                             20073
Aliens vs Predator: Requiem                   20034
La Môme                                       19281
Lonely Hearts                                 18397
Cars                                          17917
The Golden Compass                            17903
Grbavica                                      17624
The Devil Wears Prada                         16811
Astérix aux Jeux Olympiques                   16236
Street Kings                                  16135
Montag kommen die Fenster                     15879
We Own the Night                              15582
                                              ...
Will You Still Love Me Tomorrow?                  1
Desolation Canyon                                 1
Beware of Christians                              1
The Rover                                         1
Jane Got a Gun                                    1
Last Man Standing                                 1
Die Farbe des Ozeans                              1
Wrong Cops                                        1
The Rise                                          1
Berberian Sound Studio                            1
Wyjazd Integracyjny                               1
Benigni                                           1
Jagten                                            1
The Purge                                         1
Άλπεις                                            1
The Price of Sex                                  1
Ja saapuu oikea yö                                1
Yellow Rock                                       1
Behind the Candelabra                             1
Sağ Salim                                         1
Scary or Die                                      1
Zero Charisma                                     1
Down and Dangerous                                1
Intersections                                     1
Pas Douce                                         1
Drift                                             1
Scrambled Beer                                    1
Instructions for a Light & Sound Machine          1
Seal Team Six: The Raid on Osama Bin Laden        1
August Evening                                    1
Name: rating, Length: 2118, dtype: int64

In [26]:
ratings = pd.DataFrame(df.groupby("original_title")['rating'].mean())
ratings.head()

                         rating
original_title
!Women Art Revolution  2.802945
$5 a Day               2.246795
(A)Sexual              3.583333
10 Items or Less       4.081794
10,000 BC              3.653499

In [27]:
ratings['num of ratings']=pd.DataFrame(df.groupby('original_title')['rating'].count())

In [ ]:
movie_table = df.pivot_table(index="UserId",columns='original_title',values='rating')
movie_table.info()

In [ ]:
ratings.sort_values('num of ratings',ascending=False).head()

In [ ]:
EVA_user_ratings = movie_table['EVA']

In [ ]:
movie_table.corrwith(EVA_user_ratings)

In [ ]:
similar_to_EVA = movie_table.corrwith(EVA_user_ratings)

In [ ]:
corr_EVA = pd.DataFrame(similar_to_EVA,columns = ['Correlation'])

In [ ]:
corr_EVA.dropna(inplace=True)

In [ ]:
corr_EVA = corr_EVA.join(ratings['num of ratings'])

In [ ]:
corr_EVA.head()

In [ ]:
corr_EVA[corr_EVA['num of ratings']>50].sort_values('Correlation',ascending=False)